37 db client
lsd-maddrive/schedulebot pull request #66
Opened 2023-03-05 18:13 UTC by Areemi

2023-03-05 19:01 UTC, serykhelena requested changes

2023-03-05 19:01 UTC, serykhelena commented on schedulebot/db/client.py
> +        key = 'DB_DPATH'
Вынести это в атрибуты класса, пожалуйста. 
Благодаря этому, мы сможем дальше при необходимости, доставать эту константу извне. Например, `DatabaseClient.key`

Т.е. 

```
class DatabaseClient():
    key = 'DB_DPATH'
   def __init__(self): 
     ... 
     self.db_dpath = os.getenv(self.key)
```

2023-03-05 19:01 UTC, serykhelena commented on schedulebot/db/client.py
> +        self.DB_DPATH = os.getenv(key)
self.DB_DPATH сделай маленькими буквами (`self.db_dpath`), внутри класса все константы пишутся маленькими буквами, вне классов константы пишутся большими буквами по PEP

2023-03-05 19:01 UTC, serykhelena commented on schedulebot/db/client.py
> +        else:
else можно убрать, т.к. если первое условие выполнится, то дальше код не пойдёт, т.е. 

```
if self.DB_DPATH is None:
            raise ValueError("DB_DPATH = None")

os.makedirs(self.DB_DPATH, exist_ok=True)
...
```

2023-03-05 19:01 UTC, serykhelena commented on schedulebot/db/client.py
> +            PATH_TO_DB = os.path.join(self.DB_DPATH, 'data.db')
PATH_TO_DB можно сразу обозвать self.sqlite_filepath, зачем тратить память на ещё одну переменную (=

2023-03-05 19:01 UTC, serykhelena commented on schedulebot/db/client.py
> +        engine = sql.create_engine(f"sqlite:///{self.sqlite_filepath}")
Добавь после создания engine строчку логов, что engine был успешно создан  по пути self.sqlite_filepath. Можно уровнем INFO

2023-03-05 21:36 UTC, Areemi commented on schedulebot/db/client.py
> +        key = 'DB_DPATH'
Только key нужно вынести из метода?

2023-03-05 21:44 UTC, Areemi commented on schedulebot/db/client.py
> +        engine = sql.create_engine(f"sqlite:///{self.sqlite_filepath}")
logging.info('engine был успешно создан по пути self.sqlite_filepath')?

2023-03-06 06:28 UTC, serykhelena commented on schedulebot/db/client.py
> +        key = 'DB_DPATH'
Да, это не обящательно, просто на мой взгляд так код станет чище. И если нам нужна будет эта константа, мы сможем достать её из класса, не создавая экземпляр при этом, типа чуть меньше памяти потребуется

2023-03-06 06:29 UTC, serykhelena commented on schedulebot/db/client.py
> +        engine = sql.create_engine(f"sqlite:///{self.sqlite_filepath}")
Внутри метода, после строчки 22, чтобы видеть, что база создаётся по правильному пути. Только давай сразу на английском (= 
И только не logging.info, а используя объект логера `self._logger.info(f"The engine {self.sqlite_filepath} was created successfully")`

2023-03-06 10:10 UTC, serykhelena approved these changes

2023-03-06 10:11 UTC, merged