52 filling in the teacher subject table
lsd-maddrive/schedulebot pull request #82
Opened 2023-05-07 16:11 UTC by Areemi

2023-05-07 16:46 UTC, serykhelena requested changes

2023-05-07 16:46 UTC, serykhelena commented on schedulebot/db/client.py
> +            x = [val[0] for val in session.query(table.id).filter(table.first_name.like(first),
Я предлагаю переделать метод get_id на более универсальный, чтобы под каждую таблицу не плодить дальше методы. Этот метод будет работать только для таблицы, у которой есть колонки first_name, middle_name etc. 

Я предлагаю сделать примерно так 

```
def get_id(self, table, conditions: list):
        with self._session() as session:
            record = session.query(table).filter(and_(*conditions))[0]
        return record.id
```

Где conditions - это список условий, который формируется снаруже, в нашем случае в скрипте load_data.py

2023-05-07 16:46 UTC, serykhelena commented on scripts/load_data.py
> +        if column != 'Unnamed: 0' and column != 'subjects':
Чтобы в датафрейме не было колонки 'Unnamed: 0', при чтении данных можно явно задать столбец с индексами, т.е. subject_df = pd.read_csv(fpath_sub, index_col=0)

2023-05-07 16:46 UTC, serykhelena commented on scripts/load_data.py
> +            for index in subject_df[column]:
Чтобы убрать эти вложенные циклы можно использовать 
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html 

Либо, можно сформировать сразу список предметов и список списокв преподавателей к ним 
 subjects = subject_df["subjects"].values
 teachers_info = subject_df.apply(lambda row: row[row == 1].index.values, axis=1).values

2023-05-07 16:46 UTC, serykhelena commented on scripts/load_data.py
> +                    record = Teacher_subject(teacher_id=teacher_index, subject_id=subject_index)
Пропустила в предыдущем PR, но классы в питоне называются через camelCase, а не через snake_case
Переименуй, пожалуйста, Teacher_subject -> TeacherSubject (только класс, имя таблицы оставь как было(

2023-05-07 18:51 UTC, serykhelena requested changes

2023-05-07 18:51 UTC, serykhelena commented on scripts/load_data.py
> +    teachers = db_client.get_id_list(Weekdays)
почему weekdays находятся в переменной teachers? 
А временные интервалы в subjects?

2023-05-07 18:51 UTC, serykhelena commented on scripts/load_data.py
> +            subject_index = db_client.get_id(Subject, [Subject.name.like(subject)])
Это достаточно сделать 1 раз, т.к. в данных у тебя одному предмету соответствует несколько преподавателей. Т.е. можно вынести из второго цикла и оставить только в 1-м

2023-05-07 18:51 UTC, serykhelena commented on scripts/load_data.py
> +            teacher_name = name.split()
сделай расспаковку данных в переменные, чтобы было понятнее, где есть что в teacher_name

2023-05-07 22:40 UTC, Areemi commented on scripts/load_data.py
> +    teachers = db_client.get_id_list(Weekdays)
а это очень хороший вопрос))))))

2023-05-08 06:57 UTC, serykhelena requested changes

2023-05-08 06:57 UTC, serykhelena commented on scripts/load_data.py
> +            name, middle_name, last_name = name.split()
Здесь ошибка, в имени также содержится должность, поэтому split можно ограничить. Например, name.split()[:-1]

2023-05-08 06:57 UTC, serykhelena commented on scripts/load_data.py
> +            conditions = [Teacher.first_name.like(name),
Также похоже, что ты распаковываешь не в том порядке, в котором ты записывал преподавателей в БД 

![image](https://user-images.githubusercontent.com/26322075/236755459-ea3c8da8-847f-4034-b955-6cba1b406bdd.png)

В БД "Дикун" - это middle name
А у тебя это переменная name 
и т.д.

2023-05-08 06:59 UTC, serykhelena commented on scripts/load_data.py
> +            conditions = [Teacher.first_name.like(name),
Позапускай скрипт и проверь, что всё работает
Также нужно влить в эту ветку свежий develop и поправить конфликты

2023-05-08 11:56 UTC, serykhelena approved these changes

2023-05-08 11:57 UTC, merged