58 filling in the table subject room
lsd-maddrive/schedulebot pull request #88
Opened 2023-05-11 18:01 UTC by Areemi

2023-05-11 18:23 UTC, serykhelena requested changes

2023-05-11 18:23 UTC, serykhelena commented on schedulebot/db/client.py
> +            for x in record:
Это можно сделать вне контекстного менеджера сессии, т.е. после 
И заменить на list comprehensions 
filter_ids = [rec.id for rec in record]

2023-05-11 18:23 UTC, serykhelena commented on schedulebot/utils/load.py
> +def subject_type_to_room_type():
Это не надо, ID нужно доставать из БД

2023-05-11 18:23 UTC, serykhelena commented on scripts/load_data.py
> +            subject_id_map = subject_type_to_room_type()
Это надо через eng_room_type и из БД тащить

2023-05-11 18:23 UTC, serykhelena commented on schedulebot/utils/load.py
> +        'пр.': [3, 4],
А почему несколько ID-шников?

2023-05-11 18:28 UTC, Areemi commented on schedulebot/utils/load.py
> +        'пр.': [3, 4],
есть аудитории, которые мы назвали mixed, в них проводяь лекции, лабы и практики

2023-05-11 19:19 UTC, serykhelena requested changes

2023-05-11 19:19 UTC, serykhelena commented on scripts/load_data.py
> +    mixed_id = db_client.get_filter_ids(Room, conditions=[Room.type_id.like(4)])
Вот тут дело в том, чтомы изначально не знает ID нужного типа, а вдруг в БД изменится ID и тогда будет неочевидная бага 
ID типа аудитории нужно получить по значению, если тебе нужен тип mixed, сначала по значению получи ID mixed, а потом уже все аудитории

2023-05-12 07:09 UTC, serykhelena approved these changes

2023-05-12 07:09 UTC, merged